### PR TITLE
Add unit tests for database access functions

### PR DESCRIPTION
**Pull request by JoshuaKerley**

### CODE REVIEW

**Comment by yanivsagy** [comment]
All of your unit tests look good to me and you have full code coverage. When you fix the Backend CI check, it looks ready to be merged.

**Comment by daviduhlfelder** [comment]
As long as the error to push issue is resolved, it seems good to go

**Review by daviduhlfelder — APPROVED** [review]
As long as the error to push issue is resolved, it seems good to go

**Review by yanivsagy — APPROVED** [review]

**Review by RogShotz — APPROVED** [review]
lgtb

**Pull request merged**
