### PR TITLE
37-View-Event-Layout (resolves #37)

### LINKED ISSUE #37: As a ticket buyer, I want to see an event and all of its relevant information in an organized layout
Time Estimate: 3 hours
Actual time: 5 hours

### PR DESCRIPTION
**Pull request by yanivsagy**
Screen Shot 2022-05-27 at 8 33 59 PM

### CODE REVIEW

**Comment by JoshuaKerley** [comment]
Looks like it's failing the prettier check, but other than that looks good

**Comment by daviduhlfelder** [comment]
It looks good to me, and I prefer to new layout

**Comment by RogShotz** [comment]
LGTB

**Review by RogShotz — APPROVED** [review]
LGTB

**Review by daviduhlfelder — APPROVED** [review]
It looks good to me, and I prefer to new layout

**Review by JoshuaKerley — APPROVED** [review]
LGTM

**Pull request merged**
